from __future__ import print_function
from CoolProp.CoolProp import PropsSI

import numpy as np
import CoolProp

print('CoolProp version: ', CoolProp.__version__)
print('CoolProp gitrevision: ', CoolProp.__gitrevision__)
print('CoolProp fluids: ', CoolProp.__fluids__)

# Combustion calculations data
# rho_co2 = 1.98  # [kg/m3] carbon dioxide density at standard conditions
T0 = 21  # [deg C] initial carbon dioxide temperature
p0 = 1e5  # [Pa] initial carbon dioxide pressure
Mc = 0.012  # [kg/mol] carbon molar mass
Mh = 0.001  # [kg/mol] hydrogen molar mass
Mo = 0.016  # [kg/mol] carbon molar mass
Q_ch = 500  # [kJ/mol] CH combustion abount of heat generated
P = 2e6  # [kW] coal power plant power
eff = 0.3  # [-] power plant efficiency
vg = 15.2  # [m/s] maximum gas velocity for the transport pipeline design
L = 500  # [m] pipeline length
pwh = 8e6  # [Pa] wellhead compressor entry pressure
# Pipe calculations data
S = 1.5189  # [-] specific gravity of the gas (at 21C, 1 atm)
Eff = 0.9  # efficiency factor
fd = 0.01  # [-] Darcy friction factor
r_c = 3.5  # [-] compression ratio
gamma = 1.289  # [-] specific heat capacity ration for CO2
R = 8.3145  # [J/mol/K] gas constant
eff_comp = 0.7  # compressor efficiency
eff_dr = 0.9  # electrical driver efficiency
eff_pp = 0.4  # power plant efficiency

# Carbon dioxide density in the pipeline, [kg/m3]:
rho_co2 = PropsSI('D', 'T', T0 + 273, 'P', pwh, 'CO2')  # kg/m3

# Compressibility factor, [-]
Z = PropsSI('Z', 'T', T0 + 273, 'P', pwh, 'CO2')

# Amount of heat energy generated by burning 1kg of coal, [kWh/kg]:
heat = Q_ch / (Mc + Mh) / 3600

# Amount of electrical energy generated by power plant in 1h, [kWh]:
E = P

# Amount of coal required to be burned per second to generate the required amount of electrical energy, [kg]:
ch_mass = E / (heat * eff) / 3600

# Amount of CO2 produced, when 1kg of coal is burned, 1mol CH produces 1 mol CO2 (from stocheometry eqaution) [kg]:
co2_mass0 = (Mc + 2 * Mo) / (Mc + Mh)

# Amount of CO2 produced per second, [kg]:
co2_mass = ch_mass * co2_mass0

# Volumetric flow rate of CO2, [m3/s]:
q_co2 = co2_mass / rho_co2

# Required pipeline diameter, [inch]:
d = np.sqrt(4 * q_co2 / (np.pi * vg))

# Required pressure difference, Darcy Weisbach, [Pa]:
dp = fd * L * rho_co2 * vg ** 2 / 2 / d

# Required pipeline inlet pressure (1st compressor outlet pressure) [Pa]:
p_p_in = pwh + dp

# Required amount of compressor stages:
n_st = np.log(p_p_in / p0) / np.log(r_c)

# Compressibility ratio for isentropic work calculations:
Z1 = PropsSI('Z', 'T', (T0 + 273), 'P', p0, 'CO2')

# Theoretical isentropic work [J/mol]:
W_th = gamma * R * Z1 * (T0 + 273) / (gamma - 1) * ((p_p_in / p0) ** (1 - 1 / gamma) - 1)

# Practical compression work of the 1st compressor [J/mol]:
W_pr = W_th / eff_comp / eff_dr / eff_pp

print(
    'Carbon dioxide density in the pipeline = {} kg/m3.\n'
    'Compressibility factor = {}\n'
    'Volumetric flow rate of CO2 = {} m3/s.\n'
    'Required pipeline diameter = {} cm.\n'
    'Pipeline pressure difference = {} Pa = {} bar.'.format(
        float("{0:.2f}".format(rho_co2)),
        float("{0:.2f}".format(Z)),
        float("{0:.2f}".format(q_co2)),
        float("{0:.2f}".format(d / 0.3937)),
        float("{0:.2f}".format(dp)),
        float("{0:.2f}".format(dp / 1e5)))
)

# Carbon dioxide enthalpy and entropy calculations at initial conditions:
# enthalpy = PropsSI('H', 'T', T0 + 273, 'P', P0, 'CO2')
# entropy = PropsSI('S', 'T', T0 + 273, 'P', P0, 'CO2')
